name: run_tests
on: push
jobs: 
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # run on all three OS
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Check out code # download the code from my repositoroy
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.2'

      - name: Run tests
        run: python -m unittest -v
